// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-gg5mqNZLE__uO7xI_KcoZxQHawrcb4Y',
    appId: '1:555750406282:web:0739249db379bd695d5573',
    messagingSenderId: '555750406282',
    projectId: 'elearningapp-4adde',
    authDomain: 'elearningapp-4adde.firebaseapp.com',
    databaseURL: 'https://elearningapp-4adde-default-rtdb.firebaseio.com',
    storageBucket: 'elearningapp-4adde.appspot.com',
    measurementId: 'G-0NGCSG51CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmMvWpHGeKxAHmX3u8kg1ut6Sq4hgGPdk',
    appId: '1:555750406282:android:c001a1ffb7371e3a5d5573',
    messagingSenderId: '555750406282',
    projectId: 'elearningapp-4adde',
    databaseURL: 'https://elearningapp-4adde-default-rtdb.firebaseio.com',
    storageBucket: 'elearningapp-4adde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hI8LYVuMDQZfl-u3CqdgdGAmAgUPpuI',
    appId: '1:555750406282:ios:ccb3a37d16ee2e2e5d5573',
    messagingSenderId: '555750406282',
    projectId: 'elearningapp-4adde',
    databaseURL: 'https://elearningapp-4adde-default-rtdb.firebaseio.com',
    storageBucket: 'elearningapp-4adde.appspot.com',
    iosBundleId: 'com.app.eLearningDathboard',
  );
}
